// src/lib/data.ts
import type { DPA, Listing } from './types'

export const COUNTY_TAX: Record<string, number> = {
  Anoka: 0.0115, Carver: 0.0105, Chisago: 0.011, Dakota: 0.011,
  Hennepin: 0.0125, Isanti: 0.0115, Ramsey: 0.013, Scott: 0.0108,
  Sherburne: 0.011, Washington: 0.0112, Wright: 0.0108,
}

export const COUNTIES = [
  '', 'Anoka', 'Carver', 'Chisago', 'Dakota', 'Hennepin',
  'Isanti', 'Ramsey', 'Scott', 'Sherburne', 'Washington', 'Wright', 'Other MN',
]

export const PROGRAMS: DPA[] = [
  // ── STATEWIDE ─────────────────────────────────────────────────────────────
  {
    id: 'firstgen', name: 'First-Generation Homebuyers Community DPA Fund (MMCDC)', short: 'First-Gen DPA',
    max: 32000, pctCap: 10, type: 'Forgivable (5yr)', forgiveYrs: 5,
    incomeLimit: 132400, ficoMin: 0, priceLimit: 515200, status: 'closed', coverage: 'Statewide',
    url: 'firstgendpa.org', phone: 'firstgendpa.org',
    notes: '0% interest, forgiven 20%/yr over 5 years. Portal currently closed. Sharia-compliant OK.',
    reqFirstTime: false, reqFirstGen: true,
  },
  {
    id: 'welcome', name: 'Welcome Home Down Payment Assistance', short: 'Welcome Home',
    max: 50000, pctCap: 30, type: 'Forgivable (10yr)', forgiveYrs: 10,
    incomeLimit: 160000, ficoMin: 0, priceLimit: 766550, status: 'open', coverage: 'Statewide',
    url: 'nwhomepartners.org', phone: '651-292-8710',
    notes: 'Up to 30% of price capped at $50K. Approved partners only. $1K own funds required. Somali/Spanish/Hmong speakers available.',
    reqFirstTime: true, reqFirstGen: false,
  },
  {
    id: 'startup', name: 'MHFA Start Up + Deferred Payment Loan', short: 'MHFA Start Up',
    max: 18000, type: 'Deferred (0%)',
    incomeLimit: 152200, ficoMin: 640, priceLimit: 659550, status: 'open', coverage: 'Statewide',
    url: 'mnhousing.gov', phone: 'mnhousing.gov',
    notes: 'Below-market rate mortgage + up to $18K DPA. Repaid at sale or refinance.',
    reqFirstTime: true, reqFirstGen: false,
  },
  {
    id: 'stepup', name: 'MHFA Step Up Program', short: 'MHFA Step Up',
    max: 18000, type: 'Monthly Payment (10yr)',
    incomeLimit: 170000, ficoMin: 640, priceLimit: 659550, status: 'open', coverage: 'Statewide',
    url: 'mnhousing.gov', phone: 'mnhousing.gov',
    notes: 'For non-first-time buyers or those over Start Up limits. Monthly payments, 10-year term.',
    reqFirstTime: false, reqFirstGen: false,
  },
  {
    id: 'dpl', name: 'MHFA Deferred Payment Loan', short: 'MHFA DPL',
    max: 16500, type: 'Deferred (0%)',
    incomeLimit: 152200, ficoMin: 640, priceLimit: 659550, status: 'open', coverage: 'Statewide',
    url: 'mnhousing.gov', phone: 'mnhousing.gov',
    notes: 'No monthly payments. Repaid at sale, refi, or end of mortgage. Pairs with Start Up.',
    reqFirstTime: true, reqFirstGen: false,
  },
  {
    id: 'dplplus', name: 'MHFA Deferred Payment Loan Plus', short: 'MHFA DPL+',
    max: 18000, type: 'Deferred (0%)',
    incomeLimit: 152200, ficoMin: 640, priceLimit: 659550, status: 'open', coverage: 'Statewide',
    url: 'mnhousing.gov', phone: 'mnhousing.gov',
    notes: 'Enhanced version for target criteria (single parents, veterans, dependents). No monthly payments.',
    reqFirstTime: true, reqFirstGen: false,
  },
  // ── COUNTY / CITY ─────────────────────────────────────────────────────────
  {
    id: 'ramseyfg', name: 'Ramsey County FirstHome (First-Gen)', short: 'Ramsey FirstHome FG',
    max: 93150, type: 'Deferred (0%)',
    incomeLimit: 120000, ficoMin: 0, priceLimit: 372600, status: 'open', coverage: 'Suburban Ramsey County',
    url: 'ramseycountymn.gov', phone: '651-266-8000',
    notes: 'First-generation buyers in suburban Ramsey Co. Up to $93,150. Advisor + education required.',
    reqFirstTime: false, reqFirstGen: true,
  },
  {
    id: 'ramseyft', name: 'Ramsey County FirstHome (First-Time)', short: 'Ramsey FirstHome FT',
    max: 20000, type: 'Deferred (0%)',
    incomeLimit: 120000, ficoMin: 0, priceLimit: 372600, status: 'open', coverage: 'Suburban Ramsey County',
    url: 'ramseycountymn.gov', phone: '651-266-8000',
    notes: 'First-time buyers. Cities include Arden Hills, Maplewood, Roseville, Shoreview, White Bear Lake.',
    reqFirstTime: true, reqFirstGen: false,
  },
  {
    id: 'stpaul', name: 'St. Paul DPA + Inheritance Fund', short: 'St. Paul DPA',
    max: 110000, type: 'Deferred (0%)',
    incomeLimit: 120000, ficoMin: 0, priceLimit: 515200, status: 'open', coverage: 'City of St. Paul',
    url: 'stpaul.gov', phone: '651-266-6565',
    notes: '$40K base (80% AMI). First-gen +$10K. Inheritance Fund layers up to +$60K (100% AMI). Total up to $110K.',
    reqFirstTime: true, reqFirstGen: false,
  },
  {
    id: 'mpls', name: 'Homeownership Opportunity Minneapolis (HOM)', short: 'Minneapolis HOM',
    max: 20000, type: 'Deferred (30yr)',
    incomeLimit: 120000, ficoMin: 0, priceLimit: 515200, status: 'open', coverage: 'City of Minneapolis',
    url: 'minneapolismn.gov', phone: '612-673-5095',
    notes: '$10K (61-80% AMI) or $20K (below 60% AMI). 0% interest, repaid at sale/refi/payoff.',
    reqFirstTime: true, reqFirstGen: false,
  },
  {
    id: 'mplsequity', name: 'Minneapolis Building Equity', short: 'Mpls Building Equity',
    max: 40000, type: 'Forgivable (5yr)', forgiveYrs: 5,
    incomeLimit: 140000, ficoMin: 0, priceLimit: 659550, status: 'open', coverage: '7-county metro',
    url: 'minneapolismn.gov', phone: '612-673-5095',
    notes: 'For 2-4 unit buildings (duplex/triplex/fourplex). Owner-occupant landlord. 0%, forgivable.',
    reqFirstTime: false, reqFirstGen: false,
  },
  {
    id: 'dakotacda', name: 'Dakota County CDA First Time Homebuyer', short: 'Dakota CDA',
    max: 8500, type: 'Deferred (0%)',
    incomeLimit: 103900, ficoMin: 640, priceLimit: 515300, status: 'open', coverage: 'Dakota County',
    url: 'dakotacda.org', phone: '651-675-4472',
    notes: '+ MCC up to $2K/yr tax credit. Income: $90,400 (1-2 person) / $103,900 (3+ person).',
    reqFirstTime: true, reqFirstGen: false,
  },
  {
    id: 'scottcda', name: 'Scott County CDA', short: 'Scott CDA',
    max: 8000, type: 'Grant',
    incomeLimit: 103900, ficoMin: 0, priceLimit: 372600, status: 'open', coverage: 'Scott County',
    url: 'scottcda.org', phone: '952-402-9022',
    notes: '$8K grant after completing CDA counseling + education.',
    reqFirstTime: true, reqFirstGen: false,
  },
  {
    id: 'commkeys', name: 'Community Keys Plus Impact', short: 'Community Keys+',
    max: 25000, type: 'Deferred (0%)',
    incomeLimit: 106000, ficoMin: 0, priceLimit: 659550, status: 'open',
    coverage: 'Hennepin, Ramsey, Washington, Dakota, Anoka',
    url: 'nwhomepartners.org', phone: '651-292-8710',
    notes: 'Census tract may apply. MHFA Impact funds can cover FHA 3.5%. Can layer with other DPA.',
    reqFirstTime: false, reqFirstGen: false,
  },
  {
    id: 'metrohome', name: 'Metro Home Down Payment Assistance', short: 'Metro Home',
    max: 10000, type: 'Deferred (0%)',
    incomeLimit: 120000, ficoMin: 0, priceLimit: 515200, status: 'open',
    coverage: '11-county Twin Cities metro',
    url: 'nwhomepartners.org', phone: '651-292-8710',
    notes: 'Anoka, Carver, Chisago, Dakota, Hennepin, Isanti, Ramsey, Scott, Sherburne, Washington, Wright.',
    reqFirstTime: false, reqFirstGen: false,
  },
  {
    id: 'bloomington', name: 'Bloomington Homebuyer Mortgage Assistance', short: 'Bloomington HMA',
    max: 10500, type: 'Deferred (0%)',
    incomeLimit: 120000, ficoMin: 0, priceLimit: 515200, status: 'open', coverage: 'City of Bloomington',
    url: 'nwhomepartners.org', phone: '651-292-8710',
    notes: '$10,500 DPA for Bloomington buyers.',
    reqFirstTime: false, reqFirstGen: false,
  },
  {
    id: 'roseville', name: 'Roseville First-Gen DPA', short: 'Roseville FG',
    max: 25000, type: 'Deferred (0%)',
    incomeLimit: 120000, ficoMin: 0, priceLimit: 515200, status: 'open', coverage: 'City of Roseville',
    url: 'cityofroseville.com', phone: '651-792-7080',
    notes: 'First-gen buyers. $25K deferred 0% loan, repaid at sale.',
    reqFirstTime: false, reqFirstGen: true,
  },
  {
    id: 'woodbury', name: 'City of Woodbury DPA', short: 'Woodbury DPA',
    max: 30000, type: 'Low-interest',
    incomeLimit: 120000, ficoMin: 0, priceLimit: 419000, status: 'open', coverage: 'City of Woodbury',
    url: 'woodburymn.gov', phone: '651-714-3500',
    notes: 'Low-interest loan up to $30K for first-time buyers in Woodbury.',
    reqFirstTime: true, reqFirstGen: false,
  },
  {
    id: 'coonrapids', name: 'Coon Rapids DPA', short: 'Coon Rapids',
    max: 5000, type: 'Deferred (0%)',
    incomeLimit: 120000, ficoMin: 0, priceLimit: 372600, status: 'open', coverage: 'City of Coon Rapids',
    url: 'coonrapidsmn.gov', phone: '763-755-2880',
    notes: '$5K at 0% APR for costs associated with home purchase.',
    reqFirstTime: true, reqFirstGen: false,
  },
  // ── NATIONAL ──────────────────────────────────────────────────────────────
  {
    id: 'chenoa', name: 'Chenoa Fund DPA', short: 'Chenoa Fund',
    max: 20000, pctCap: 3.5, type: 'Forgivable (3yr)', forgiveYrs: 3,
    incomeLimit: 999999, ficoMin: 620, priceLimit: 552000, status: 'open', coverage: 'Nationwide',
    url: 'chenoafund.org', phone: 'chenoafund.org',
    notes: 'Covers FHA 3.5% as forgivable or repayable second mortgage.',
    reqFirstTime: false, reqFirstGen: false,
  },
  {
    id: 'naf', name: 'New American Funding DPA', short: 'NAF DPA',
    max: 6000, type: 'Deferred',
    incomeLimit: 999999, ficoMin: 620, priceLimit: 766550, status: 'open', coverage: 'Nationwide',
    url: 'newamericanfunding.com', phone: 'newamericanfunding.com',
    notes: 'Combinable with MN Housing DPA.',
    reqFirstTime: false, reqFirstGen: false,
  },
  {
    id: 'fhlbank', name: 'FHLBank Des Moines Home$tart', short: 'Home$tart',
    max: 7500, type: 'Grant',
    incomeLimit: 120000, ficoMin: 0, priceLimit: 515200, status: 'open',
    coverage: 'MN, IA, MO, ND, SD + others',
    url: 'fhlbdm.com', phone: 'fhlbdm.com',
    notes: 'Apply through a member bank. Up to $7,500 grant.',
    reqFirstTime: true, reqFirstGen: false,
  },
]

// Real new-construction listings — images resolved server-side from Zillow pages
export const CURATED: Listing[] = [
  { id: 1, name: '21878 Denton Ave, Whispering Fields', price: 317990, beds: 3, baths: 3, sqft: 1782, city: 'Farmington', builder: 'Lennar', url: 'https://www.zillow.com/farmington-mn-55024/new-homes/' },
  { id: 2, name: '21926 Wisteria Way', price: 334990, beds: 3, baths: 3, sqft: 1804, city: 'Farmington', builder: 'Lennar', url: 'https://www.zillow.com/farmington-mn-55024/new-homes/' },
  { id: 3, name: '4792 218th St W, Voyageur Farms', price: 358085, beds: 3, baths: 2, sqft: 1281, city: 'Farmington', builder: 'Lennar', url: 'https://www.zillow.com/farmington-mn/new-homes/' },
  { id: 4, name: '19139 Crystal Ter', price: 426990, beds: 3, baths: 2, sqft: 1892, city: 'Farmington', builder: 'M/I Homes', url: 'https://www.zillow.com/farmington-mn-55024/new-homes/' },
  { id: 5, name: '4884 218th Ct, Voyageur Farms', price: 460485, beds: 5, baths: 3, sqft: 2505, city: 'Farmington', builder: 'Lennar', url: 'https://www.zillow.com/farmington-mn/new-homes/' },
  { id: 6, name: '20947 Flanders Way', price: 479990, beds: 3, baths: 3, sqft: 2200, city: 'Farmington', builder: 'D.R. Horton', url: 'https://www.zillow.com/farmington-mn-55024/new-homes/' },
  { id: 7, name: 'Cordelia Ashton Plan', price: 499990, beds: 4, baths: 3, sqft: 2400, city: 'Lakeville', builder: 'D.R. Horton', url: 'https://www.zillow.com/lakeville-mn/new-homes/' },
  { id: 8, name: 'Pheasant Run 6BD', price: 515000, beds: 6, baths: 3, sqft: 2400, city: 'Lakeville', builder: 'D.R. Horton', url: 'https://www.zillow.com/lakeville-mn/new-homes/' },
]

export const CHECKLIST = [
  { id: 'credit',     label: 'Check credit score (all 3 bureaus)',  tip: 'Free at annualcreditreport.com. Lenders use FICO 2, 4, 5.' },
  { id: 'w2',         label: 'Gather 2 years W-2s / tax returns',   tip: 'Also: 2mo bank statements, 30 days paystubs, photo ID.' },
  { id: 'education',  label: 'Complete homebuyer education',         tip: 'Home Stretch or Framework online. BEFORE purchase agreement.' },
  { id: 'counselor',  label: 'Meet HUD-certified counselor',         tip: 'Free at hocmn.org.' },
  { id: 'preapproval',label: 'Get pre-approval letter',              tip: 'Shop 3+ lenders within 14 days.' },
  { id: 'dpa',        label: 'Apply for DPA programs',               tip: 'First-come, first-served. Be ready when portals open.' },
  { id: 'agent',      label: "Find a buyer's agent",                 tip: 'Typically paid by seller. Ask about First-Gen experience.' },
  { id: 'offer',      label: 'Make an offer',                        tip: 'Earnest money is typically 1-2% of price.' },
]
